export const houses = [
  {
    name: "Simba House",
    location: "Kilimani",
    price: "KSH 80,000",
    bedrooms: 3,
    bathrooms: 2,
    images: ["image1.jpg", "image2.jpg", "image3.jpg"],
    owner: {
      propertyName: "Simba Properties",
      ownerName: "Wanjiku Mwangi",
      picture: "owner_image.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Kamau's Haven",
    location: "Westlands",
    price: "KSH 120,000",
    bedrooms: 4,
    bathrooms: 3,
    images: ["image4.jpg", "image5.jpg", "image6.jpg"],
    owner: {
      propertyName: "Kamau Properties",
      ownerName: "John Kamau",
      picture: "owner_image2.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Nyawira Apartments",
    location: "Lang'ata",
    price: "KSH 60,000",
    bedrooms: 2,
    bathrooms: 1,
    images: ["image7.jpg", "image8.jpg", "image9.jpg"],
    owner: {
      propertyName: "Nyawira Holdings",
      ownerName: "Grace Nyawira",
      picture: "owner_image3.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Ole Sereni Villa",
    location: "Karen",
    price: "KSH 200,000",
    bedrooms: 5,
    bathrooms: 4,
    images: ["image10.jpg", "image11.jpg", "image12.jpg"],
    owner: {
      propertyName: "Sereni Properties",
      ownerName: "Jane Njeri",
      picture: "owner_image4.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Kawira's Oasis",
    location: "Runda",
    price: "KSH 150,000",
    bedrooms: 4,
    bathrooms: 3,
    images: ["image13.jpg", "image14.jpg", "image15.jpg"],
    owner: {
      propertyName: "Kawira Homes",
      ownerName: "David Kawira",
      picture: "owner_image5.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Makena's Hideaway",
    location: "Lavington",
    price: "KSH 180,000",
    bedrooms: 4,
    bathrooms: 3,
    images: ["image16.jpg", "image17.jpg", "image18.jpg"],
    owner: {
      propertyName: "Makena Properties",
      ownerName: "Alice Makena",
      picture: "owner_image6.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Kamau's Dream",
    location: "Kitisuru",
    price: "KSH 250,000",
    bedrooms: 5,
    bathrooms: 4,
    images: ["image19.jpg", "image20.jpg", "image21.jpg"],
    owner: {
      propertyName: "Kamau Homes",
      ownerName: "Patrick Kamau",
      picture: "owner_image7.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Wambui's Retreat",
    location: "Kileleshwa",
    price: "KSH 90,000",
    bedrooms: 3,
    bathrooms: 2,
    images: ["image22.jpg", "image23.jpg", "image24.jpg"],
    owner: {
      propertyName: "Wambui Properties",
      ownerName: "Sarah Wambui",
      picture: "owner_image8.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Muthoni's Paradise",
    location: "Parklands",
    price: "KSH 100,000",
    bedrooms: 3,
    bathrooms: 2,
    images: ["image25.jpg", "image26.jpg", "image27.jpg"],
    owner: {
      propertyName: "Muthoni Estates",
      ownerName: "Peter Muthoni",
      picture: "owner_image9.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Korir's Heights",
    location: "Ngong Road",
    price: "KSH 80,000",
    bedrooms: 2,
    bathrooms: 1,
    images: ["image28.jpg", "image29.jpg", "image30.jpg"],
    owner: {
      propertyName: "Korir Properties",
      ownerName: "Lucy Korir",
      picture: "owner_image10.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Mutua's Manor",
    location: "Thika Road",
    price: "KSH 120,000",
    bedrooms: 4,
    bathrooms: 3,
    images: ["image31.jpg", "image32.jpg", "image33.jpg"],
    owner: {
      propertyName: "Mutua Holdings",
      ownerName: "Joseph Mutua",
      picture: "owner_image11.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Wanjiku's Sanctuary",
    location: "Ruaka",
    price: "KSH 85,000",
    bedrooms: 3,
    bathrooms: 2,
    images: ["image34.jpg", "image35.jpg", "image36.jpg"],
    owner: {
      propertyName: "Wanjiku Estates",
      ownerName: "Grace Wanjiku",
      picture: "owner_image12.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Kariuki's Haven",
    location: "Ruaka",
    price: "KSH 95,000",
    bedrooms: 4,
    bathrooms: 3,
    images: ["image37.jpg", "image38.jpg", "image39.jpg"],
    owner: {
      propertyName: "Kariuki Estates",
      ownerName: "Lucas Kariuki",
      picture: "owner_image13.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Nyambura's Villa",
    location: "Ruaka",
    price: "KSH 110,000",
    bedrooms: 5,
    bathrooms: 4,
    images: ["image40.jpg", "image41.jpg", "image42.jpg"],
    owner: {
      propertyName: "Nyambura Properties",
      ownerName: "Esther Nyambura",
      picture: "owner_image14.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Kamau's Retreat",
    location: "Ruaka",
    price: "KSH 85,000",
    bedrooms: 3,
    bathrooms: 2,
    images: ["image43.jpg", "image44.jpg", "image45.jpg"],
    owner: {
      propertyName: "Kamau Holdings",
      ownerName: "Paul Kamau",
      picture: "owner_image15.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Njeri's Homestead",
    location: "Ruaka",
    price: "KSH 75,000",
    bedrooms: 2,
    bathrooms: 1,
    images: ["image46.jpg", "image47.jpg", "image48.jpg"],
    owner: {
      propertyName: "Njeri Properties",
      ownerName: "Susan Njeri",
      picture: "owner_image16.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
  {
    name: "Mwangi's Residence",
    location: "Ruaka",
    price: "KSH 120,000",
    bedrooms: 4,
    bathrooms: 3,
    images: ["image49.jpg", "image50.jpg", "image51.jpg"],
    owner: {
      propertyName: "Mwangi Estates",
      ownerName: "James Mwangi",
      picture: "owner_image17.jpg",
      phoneNumber: "+254 7XX XXX XXX",
    },
  },
];
